name: Code Quality

on:
  push:

env:
  NODE_VERSION: '24'
  PYTHON_VERSION: '3.13'

jobs:
  plugin-lint:
    name: 'Plugin: Lint'
    runs-on: ubuntu-latest

    steps:
      - name: '[setup] Check out repository'
        uses: actions/checkout@v6

      - name: '[setup] Setup Node.js'
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: '[app] Install'
        working-directory: ./plugin
        run: npm install

      - name: '[check] Run ESLint'
        working-directory: ./plugin
        run: npm run lint

  plugin-typecheck:
    name: 'Plugin: Typecheck'
    runs-on: ubuntu-latest

    steps:
      - name: '[setup] Check out repository'
        uses: actions/checkout@v6

      - name: '[setup] Setup Node.js'
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: '[app] Install'
        working-directory: ./plugin
        run: npm install

      - name: '[check] Run TypeScript typecheck'
        working-directory: ./plugin
        run: npm run typecheck

  plugin-format:
    name: 'Plugin: Format Check'
    runs-on: ubuntu-latest

    steps:
      - name: '[setup] Check out repository'
        uses: actions/checkout@v6

      - name: '[setup] Setup Node.js'
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: '[app] Install'
        working-directory: ./plugin
        run: npm install

      - name: '[check] Run Prettier check'
        working-directory: ./plugin
        run: npm run format:check

  service-lint:
    name: 'Service: Lint'
    runs-on: ubuntu-latest

    steps:
      - name: '[setup] Check out repository'
        uses: actions/checkout@v6

      - name: '[setup] Install uv'
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: '[setup] Set up Python'
        working-directory: ./service
        run: uv python install

      - name: '[app] Install'
        working-directory: ./service
        run: make install

      - name: '[check] Run Ruff'
        working-directory: ./service
        run: make lint

  service-typecheck:
    name: 'Service: Typecheck'
    runs-on: ubuntu-latest

    steps:
      - name: '[setup] Check out repository'
        uses: actions/checkout@v6

      - name: '[setup] Install uv'
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: '[setup] Set up Python'
        working-directory: ./service
        run: uv python install

      - name: '[app] Install dependencies'
        working-directory: ./service
        run: make install

      - name: '[check] Run Ruff'
        working-directory: ./service
        run: make typecheck
