name: Package

on:
  push:

env:
  NODE_VERSION: '24'
  PYTHON_VERSION: '3.13'

jobs:
  plugin-zip:
    name: 'Plugin: ZIP Package'
    runs-on: ubuntu-latest

    steps:
      - name: '[setup] Checkout Project'
        uses: actions/checkout@v6

      - name: '[setup] Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v6
        with:
            node-version: ${{ env.NODE_VERSION }}

      - name: '[app] Install'
        working-directory: ./plugin
        run: npm install

      - name: '[app] Build'
        working-directory: ./plugin
        run: npm run build

      - name: '[dist] Create artifact'
        uses: actions/upload-artifact@v6
        with:
          name: plugin
          path: ./plugin/dist

  service-package:
    name: 'Service: Python Package'
    runs-on: ubuntu-latest

    steps:
      - name: '[setup] Checkout Project'
        uses: actions/checkout@v6

      - name: '[setup] Install uv'
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: '[setup] Set up Python'
        working-directory: ./service
        run: uv python install

      - name: '[app] Build'
        working-directory: ./service
        run: make build

      - name: '[dist] Create artifact'
        uses: actions/upload-artifact@v6
        with:
          name: service
          path: ./service/dist

